on: [push]

name: GettingStarted_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ https://registyforuni.azurecr.io }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and Push Docker Image to ACR'
      run: |
        docker build . -t ${{ https://registyforuni.azurecr.io }}/${{ secrets.REPOSITORY_NAME }}:${{ github.run_number }}
        docker push ${{ https://registyforuni.azurecr.io }}/${{ secrets.REPOSITORY_NAME }}:${{ github.run_number }}

    - name: 'Deploy to Azure Container Instances'
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: getting-started-${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REPOSITORY_NAME }}:${{ github.run_number }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: getting-started-github
        location: 'northeurope'
        ports: '3000'
